#include "desktop/theme/ThemeSync.hpp"
#include "config/appearance/AppearancePalette.hpp"
#include "config/desktop/DesktopPreferences.hpp"
#include "desktop/theme/FcitxTheme.hpp"
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QProcess>
#include <QSaveFile>
#include <QSettings>
#include <QStandardPaths>
#include <QTimer>
#include <QUrl>

namespace LunaDash {
namespace {
bool write(const QString &path, const QByteArray &text, QString *error) {
  if (!QDir().mkpath(QFileInfo(path).absolutePath())) {
    *error = "Could not create theme directory.";
    return false;
  }
  QSaveFile file(path);
  if (!file.open(QIODevice::WriteOnly) || file.write(text) != text.size() ||
      !file.commit()) {
    *error = file.errorString();
    return false;
  }
  return true;
}
bool includeOnce(const QString &path, const QByteArray &line, QString *error) {
  QFile file(path);
  QByteArray text;
  if (file.exists()) {
    if (!file.open(QIODevice::ReadOnly) || file.size() > 1024 * 1024) {
      *error =
          "Theme integration requires a readable configuration below 1 MiB: " +
          path;
      return false;
    }
    text = file.readAll();
    if (text.contains(line))
      return true;
    // Keep the first pre-integration configuration for manual restoration.
    if (!QFileInfo::exists(path + ".lunadash-backup") &&
        !file.copy(path + ".lunadash-backup")) {
      *error = "Could not back up configuration: " + path;
      return false;
    }
  }
  return write(path,
               line.startsWith("@import") ? line + "\n" + text
                                          : text + "\n" + line + "\n",
               error);
}
void setColorScheme(bool dark) {
  const auto program = QStandardPaths::findExecutable("gsettings");
  if (program.isEmpty())
    return;
  auto *process = new QProcess(QCoreApplication::instance());
  auto *timer = new QTimer(process);
  timer->setSingleShot(true);
  QObject::connect(timer, &QTimer::timeout, process,
                   [process] { process->kill(); });
  QObject::connect(process, &QProcess::finished, process,
                   &QObject::deleteLater);
  QObject::connect(process, &QProcess::errorOccurred, process,
                   [process](QProcess::ProcessError error) {
                     if (error == QProcess::FailedToStart)
                       process->deleteLater();
                   });
  process->setStandardOutputFile(QProcess::nullDevice());
  process->setStandardErrorFile(QProcess::nullDevice());
  process->start(program, {"set", "org.gnome.desktop.interface", "color-scheme",
                           dark ? "prefer-dark" : "prefer-light"});
  timer->start(3000);
}
} // namespace

QJsonObject synchronizeApplicationTheme() {
  static QByteArray previous;
  static QJsonObject result;
  const auto preferences = desktopPreferences();
  const auto palette = appearancePalette(preferences);
  const bool enabled = preferences.value("syncApplicationThemes").toBool();
  const bool fcitx = preferences.value("syncFcitxTheme").toBool();
  const auto fingerprint =
      QJsonDocument(palette).toJson(QJsonDocument::Compact) +
      (enabled ? "1" : "0") + (fcitx ? "1" : "0");
  if (fingerprint == previous)
    return result;
  previous = fingerprint;
  const auto config =
      QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
  const auto directory = config + "/lunadash/theme";
  result = {{"enabled", enabled}, {"directory", directory}, {"error", ""}};
  QString fcitxError;
  if (fcitx && !synchronizeFcitxTheme(palette, &fcitxError))
    result["error"] = fcitxError;

  // The desktop light/dark preference is a system preference, not an
  // application-theme override. Publish it even when optional GTK/Kitty theme
  // file synchronization is disabled so native GTK applications and other
  // consumers of org.gnome.desktop.interface follow LunaDash as well.
  setColorScheme(palette.value("dark").toBool());

  if (!enabled)
    return result;
  const auto color = [&palette](const QString &key) {
    return palette.value(key).toString();
  };
  QString error;
  const auto gtk =
      QString("@define-color theme_bg_color %1;\n@define-color theme_fg_color "
              "%2;\n@define-color theme_base_color %3;\n@define-color "
              "theme_selected_bg_color %4;\n@define-color "
              "theme_selected_fg_color %5;\n@define-color accent_color "
              "%4;\n@define-color accent_bg_color %4;\n@define-color "
              "accent_fg_color %5;\n@define-color window_bg_color "
              "%1;\n@define-color window_fg_color %2;\n@define-color "
              "view_bg_color %3;\n@define-color view_fg_color %2;\n")
          .arg(color("background"), color("text"), color("surface"),
               color("accent"), color("accentInk"));
  const auto kitty =
      QString("# Generated by LunaDash. Include from kitty.conf.\nbackground "
              "%1\nforeground %2\nselection_background "
              "%3\nselection_foreground %4\ncursor %3\nurl_color %3\n")
          .arg(color("background"), color("text"), color("accent"),
               color("accentInk"));
  if (!write(directory + "/gtk.css", gtk.toUtf8(), &error) ||
      !write(directory + "/kitty.conf", kitty.toUtf8(), &error)) {
    result["error"] = error;
    return result;
  }
  const auto import = "@import url(\"" +
                      QUrl::fromLocalFile(directory + "/gtk.css").toEncoded() +
                      "\");";
  for (const auto &version : {"gtk-3.0", "gtk-4.0"}) {
    const auto base = config + "/" + version;
    if (!includeOnce(base + "/gtk.css", import, &error))
      break;
    QSettings settings(base + "/settings.ini", QSettings::IniFormat);
    settings.setValue("Settings/gtk-application-prefer-dark-theme",
                      palette.value("dark").toBool() ? 1 : 0);
    settings.sync();
    if (settings.status() != QSettings::NoError) {
      error = "Could not save GTK theme preference.";
      break;
    }
  }
  const auto kittyConfig = config + "/kitty/kitty.conf";
  if (error.isEmpty() && QFileInfo::exists(kittyConfig))
    includeOnce(kittyConfig, QByteArray("include ../lunadash/theme/kitty.conf"),
                &error);
  result["error"] = error.isEmpty() ? fcitxError : error;
  return result;
}
} // namespace LunaDash
