#pragma once

#include <GL/glcorearb.h>
#include <stddef.h>

#ifdef __cplusplus
namespace LuDash {
extern "C" {
#endif

typedef void (*LuDashGLProc)(void);
typedef LuDashGLProc (*LuDashGLResolver)(const char *name);

typedef struct LuDashGLDispatch {
  PFNGLCREATESHADERPROC CreateShader;
  PFNGLSHADERSOURCEPROC ShaderSource;
  PFNGLCOMPILESHADERPROC CompileShader;
  PFNGLGETSHADERIVPROC GetShaderiv;
  PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
  PFNGLDELETESHADERPROC DeleteShader;
  PFNGLCREATEPROGRAMPROC CreateProgram;
  PFNGLATTACHSHADERPROC AttachShader;
  PFNGLLINKPROGRAMPROC LinkProgram;
  PFNGLGETPROGRAMIVPROC GetProgramiv;
  PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
  PFNGLDELETEPROGRAMPROC DeleteProgram;
  PFNGLUSEPROGRAMPROC UseProgram;
  PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
  PFNGLUNIFORM1IPROC Uniform1i;
  PFNGLUNIFORM1FPROC Uniform1f;
  PFNGLUNIFORM1FVPROC Uniform1fv;
  PFNGLUNIFORM2FPROC Uniform2f;
  PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
  PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
  PFNGLBINDVERTEXARRAYPROC BindVertexArray;
  PFNGLDRAWARRAYSPROC DrawArrays;
  PFNGLGETINTEGERVPROC GetIntegerv;
  PFNGLVIEWPORTPROC Viewport;
  PFNGLENABLEPROC Enable;
  PFNGLDISABLEPROC Disable;
  PFNGLDEPTHMASKPROC DepthMask;
  PFNGLCOLORMASKPROC ColorMask;
  PFNGLBLENDFUNCPROC BlendFunc;
  PFNGLSCISSORPROC Scissor;
  PFNGLSTENCILFUNCPROC StencilFunc;
  PFNGLSTENCILOPPROC StencilOp;
  PFNGLGENTEXTURESPROC GenTextures;
  PFNGLDELETETEXTURESPROC DeleteTextures;
  PFNGLACTIVETEXTUREPROC ActiveTexture;
  PFNGLBINDTEXTUREPROC BindTexture;
  PFNGLTEXPARAMETERIPROC TexParameteri;
  PFNGLTEXIMAGE2DPROC TexImage2D;
  PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
  PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
  PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
  PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
  PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
  PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
} LuDashGLDispatch;

int ludash_gl_load(LuDashGLDispatch *gl, LuDashGLResolver resolve, char *error,
                   size_t capacity);

#ifdef __cplusplus
}
}
#endif
