#include "compositor/xwayland/XWaylandSupport/XWaylandSupport.hpp"
#include <QDataStream>
#include <QDir>
#include <QFile>
#include <QRandomGenerator>
#include <QStandardPaths>
#include <cstring>
#include <fcntl.h>
#include <limits>
#include <signal.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>
namespace LuDash {
namespace {
bool writeAuthority(const QString &path,const QString &display){QFile file(path);if(!file.open(QIODevice::WriteOnly|QIODevice::NewOnly))return false;if(!file.setPermissions(QFile::ReadOwner|QFile::WriteOwner))return false;QByteArray cookie(16,Qt::Uninitialized);for(int i=0;i<16;i+=4){const auto value=QRandomGenerator::system()->generate();std::memcpy(cookie.data()+i,&value,4);}QDataStream stream(&file);stream.setByteOrder(QDataStream::BigEndian);stream<<quint16(65535);for(const auto &field:{QByteArray(),display.mid(1).toUtf8(),QByteArray("MIT-MAGIC-COOKIE-1"),cookie}){if(field.size()>std::numeric_limits<quint16>::max())return false;const auto length=static_cast<int>(field.size());stream<<static_cast<quint16>(length);if(stream.writeRawData(field.constData(),length)!=length)return false;}return stream.status()==QDataStream::Ok&&file.flush();}
}
XWaylandSupport::XWaylandSupport(QObject *parent):QObject(parent){server_.setProcessChannelMode(QProcess::ForwardedErrorChannel);connect(&server_,&QProcess::readyReadStandardOutput,this,[this]{server_.readAllStandardOutput();});connect(&server_,&QProcess::started,this,[this]{groupId_=server_.processId();if(descriptor_>=0){::close(descriptor_);descriptor_=-1;}});connect(&server_,&QProcess::errorOccurred,this,[this](QProcess::ProcessError){if(!stopping_)error_=server_.errorString();});connect(&server_,&QProcess::finished,this,[this](int code,QProcess::ExitStatus status){if(!stopping_&&(code||status!=QProcess::NormalExit))error_="XWayland compatibility service stopped unexpectedly.";if(groupId_>0)::kill(-static_cast<pid_t>(groupId_),SIGTERM);groupId_=0;releaseSocket();});}
XWaylandSupport::~XWaylandSupport(){stop();if(!server_.waitForFinished(1500)&&server_.state()!=QProcess::NotRunning){if(groupId_>0)::kill(-static_cast<pid_t>(groupId_),SIGKILL);server_.kill();server_.waitForFinished(1000);}const auto remaining=clients_;for(auto *client:remaining)if(client->state()!=QProcess::NotRunning){client->kill();client->waitForFinished(1000);}releaseSocket();}
void XWaylandSupport::releaseSocket(){if(descriptor_>=0){::close(descriptor_);descriptor_=-1;}if(!socketPath_.isEmpty()){QFile::remove(socketPath_);socketPath_.clear();}}
bool XWaylandSupport::start(const QProcessEnvironment &environment,const QSize &screenSize){const auto executable=QStandardPaths::findExecutable("Xwayland");if(executable.isEmpty()){error_="Install Xwayland for X11 applications.";return false;}if(!QDir("/tmp/.X11-unix").exists()){error_="The system X11 socket directory is unavailable.";return false;}releaseSocket();display_.clear();error_.clear();stopping_=false;environment_=environment;runtime_=std::make_unique<QTemporaryDir>(QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation)+"/ludash-xwayland-XXXXXX");if(!runtime_->isValid()){error_="Could not create a private XWayland runtime directory.";return false;}for(int number=100;number<1000;++number){if(QFile::exists(QString("/tmp/.X%1-lock").arg(number)))continue;descriptor_=::socket(AF_UNIX,SOCK_STREAM|SOCK_CLOEXEC,0);if(descriptor_<0)break;const auto path=QString("/tmp/.X11-unix/X%1").arg(number);sockaddr_un address{};address.sun_family=AF_UNIX;const auto bytes=path.toLocal8Bit();std::memcpy(address.sun_path,bytes.constData(),static_cast<size_t>(bytes.size())+1);if(::bind(descriptor_,reinterpret_cast<sockaddr *>(&address),sizeof(address))==0){socketPath_=path;if(::chmod(bytes.constData(),0600)==0&&::listen(descriptor_,16)==0){display_=":"+QString::number(number);break;}releaseSocket();break;}::close(descriptor_);descriptor_=-1;}if(descriptor_<0||display_.isEmpty()){error_="Could not reserve a private X11 display socket.";return false;}authority_=runtime_->path()+"/authority";if(!writeAuthority(authority_,display_)){error_="Could not write XWayland authentication.";releaseSocket();return false;}auto serverEnvironment=environment_;serverEnvironment.insert("XAUTHORITY",authority_);serverEnvironment.remove("DISPLAY");serverEnvironment.remove("NOTIFY_SOCKET");server_.setProcessEnvironment(serverEnvironment);const int descriptor=descriptor_;server_.setChildProcessModifier([descriptor]{if(::setsid()<0||::fcntl(descriptor,F_SETFD,0)<0)::_exit(127);});QStringList arguments{display_,"-listenfd",QString::number(descriptor_),"-auth",authority_,"-nolisten","tcp"};arguments<<"-geometry"<<QString("%1x%2").arg(qMax(320,screenSize.width())).arg(qMax(240,screenSize.height()));server_.setProgram(executable);server_.setArguments(arguments);return true;}
void XWaylandSupport::stop(){if(stopping_)return;stopping_=true;for(auto *client:clients_)if(client->state()!=QProcess::NotRunning)client->terminate();if(groupId_>0)::kill(-static_cast<pid_t>(groupId_),SIGTERM);else if(server_.state()!=QProcess::NotRunning)server_.terminate();}
bool XWaylandSupport::stopped()const{return server_.state()==QProcess::NotRunning;}
bool XWaylandSupport::startServer(QString *error){if(stopping_||server_.program().isEmpty()||!error_.isEmpty()){if(error)*error=error_.isEmpty()?"XWayland is not configured.":error_;return false;}if(server_.state()==QProcess::NotRunning){server_.start();if(!server_.waitForStarted(1000)){error_=server_.errorString();if(error)*error=error_;return false;}}return true;}
QJsonObject XWaylandSupport::snapshot()const{return{{"available",!stopping_&&!server_.program().isEmpty()&&error_.isEmpty()},{"mode","rootful-accelerated"},{"running",!stopping_&&server_.state()==QProcess::Running},{"display",display_},{"authority",authority_},{"error",error_}};}
void XWaylandSupport::applyEnvironment(QProcessEnvironment &environment)const{if(!display_.isEmpty()&&error_.isEmpty()&&!stopping_){environment.insert("DISPLAY",display_);environment.insert("XAUTHORITY",authority_);}else{environment.remove("DISPLAY");environment.remove("XAUTHORITY");}}
bool XWaylandSupport::launch(const QStringList &command,QString *error){if(command.isEmpty()||command.size()>64){if(error)*error="Enter an executable and its arguments.";return false;}const QString executable=QStandardPaths::findExecutable(command.first());if(executable.isEmpty()){if(error)*error="Executable not found: "+command.first();return false;}auto *process=new QProcess(this);auto environment=environment_;if(stopping_||server_.program().isEmpty()||!error_.isEmpty()){if(error)*error=error_.isEmpty()?"XWayland is not running.":error_;process->deleteLater();return false;}if(descriptor_<0&&!start(environment_)){if(error)*error=error_;process->deleteLater();return false;}if(!startServer(error)){process->deleteLater();return false;}applyEnvironment(environment);environment.remove("WAYLAND_DISPLAY");environment.insert("QT_QPA_PLATFORM","xcb");environment.insert("GDK_BACKEND","x11");environment.insert("SDL_VIDEODRIVER","x11");environment.insert("_JAVA_AWT_WM_NONREPARENTING","1");environment.remove("LIBGL_ALWAYS_SOFTWARE");process->setProcessEnvironment(environment);process->setProcessChannelMode(QProcess::ForwardedChannels);clients_<<process;connect(process,&QProcess::finished,this,[this,process]{clients_.removeAll(process);process->deleteLater();});connect(process,&QProcess::finished,this,[process](int code,QProcess::ExitStatus status){if(code!=0||status!=QProcess::NormalExit)qWarning().noquote()<<"LunaDash client exited abnormally:" <<process->program()<<"code"<<code<<"status"<<status;});process->start(executable,command.mid(1));return true;}
} // namespace LuDash
