cmake_minimum_required(VERSION 3.21)
project(LunaDash VERSION 0.1.0 LANGUAGES C CXX)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
include(GNUInstallDirs)
option(LUDASH_ENABLE_SANITIZERS "Enable ASan and UBSan for project code" OFF)
option(LUDASH_BUILD_EXAMPLE_PLUGIN "Build the metadata-based fade effect example" ON)
if(LUDASH_ENABLE_SANITIZERS)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        message(FATAL_ERROR "Sanitizers require GCC or Clang")
    endif()
    add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all)
    add_link_options(-fsanitize=address,undefined)
endif()
if(CMAKE_CXX_CLANG_TIDY AND NOT CMAKE_C_CLANG_TIDY)
    set(CMAKE_C_CLANG_TIDY "${CMAKE_CXX_CLANG_TIDY}")
endif()
find_path(LUDASH_GL_INCLUDE_DIR GL/glcorearb.h REQUIRED)
find_package(Qt6 6.4 REQUIRED COMPONENTS Widgets Concurrent Quick OpenGL Network DBus WaylandCompositor)
find_package(PkgConfig REQUIRED)
pkg_check_modules(WAYLAND_SERVER REQUIRED IMPORTED_TARGET wayland-server)
pkg_check_modules(WAYLAND_CLIENT REQUIRED IMPORTED_TARGET wayland-client)
find_program(WAYLAND_SCANNER wayland-scanner REQUIRED)
execute_process(COMMAND git rev-parse --verify HEAD WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} OUTPUT_VARIABLE LUNADASH_GIT_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT LUNADASH_GIT_COMMIT)
    set(LUNADASH_GIT_COMMIT "unknown")
endif()

add_library(ludash-localization src/config/Localization/Localization.cpp)
target_include_directories(ludash-localization PUBLIC src)
target_link_libraries(ludash-localization PUBLIC Qt6::Core)
qt_add_resources(ludash-localization translations PREFIX /LuDash FILES data/translations/en_US.json data/translations/zh_TW.json)
add_library(ludash-render-core src/compositor/render/GLDispatch/GLDispatch.c src/compositor/render/ShaderProgram/ShaderProgram.c src/compositor/render/WallpaperPass/WallpaperPass.c src/compositor/render/BlurPass/BlurPass.c)
target_include_directories(ludash-render-core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src ${LUDASH_GL_INCLUDE_DIR})
target_link_libraries(ludash-render-core PRIVATE m)
target_compile_options(ludash-render-core PRIVATE -Wall -Wextra -Wpedantic)
add_library(ludash-renderer src/compositor/render/RenderBackend/RenderBackend.cpp src/compositor/render/WallpaperItem/WallpaperItem.cpp src/compositor/render/WallpaperRenderer/WallpaperRenderer.cpp)
add_library(ludash-shell-renderer src/compositor/render/ShellRenderer/ShellRenderer.cpp)
target_include_directories(ludash-shell-renderer PUBLIC src)
target_link_libraries(ludash-shell-renderer PUBLIC Qt6::Core)
target_include_directories(ludash-renderer PUBLIC src)
target_link_libraries(ludash-renderer PUBLIC ludash-render-core Qt6::Quick Qt6::OpenGL)
qt_add_resources(ludash-renderer renderer_shaders PREFIX /LuDash FILES data/shaders/wallpaper.vert data/shaders/wallpaper.frag data/shaders/blur/blur.vert data/shaders/blur/blur.frag)
add_library(ludash-blur src/compositor/render/BlurItem/BlurItem.cpp src/compositor/render/BlurNode/BlurNode.cpp src/compositor/render/BlurGeometry/BlurGeometry.cpp)
target_include_directories(ludash-blur PUBLIC src)
target_link_libraries(ludash-blur PUBLIC ludash-renderer Qt6::Quick Qt6::OpenGL)
add_library(ludash-animation src/compositor/render/WindowAnimations/WindowAnimations.cpp)
target_include_directories(ludash-animation PUBLIC src)
target_link_libraries(ludash-animation PUBLIC Qt6::Quick)
add_library(ludash-xwayland src/compositor/xwayland/XWaylandSupport/XWaylandSupport.cpp)
target_include_directories(ludash-xwayland PUBLIC src)
target_link_libraries(ludash-xwayland PUBLIC Qt6::Core)
add_library(ludash-wallpaper src/desktop/WallpaperSettings/WallpaperSettings.cpp)
target_include_directories(ludash-wallpaper PUBLIC src)
target_link_libraries(ludash-wallpaper PUBLIC Qt6::Gui)
target_compile_definitions(ludash-wallpaper PRIVATE LUDASH_WALLPAPER_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}/data/wallpapers")
add_library(ludash-configuration src/config/DesktopPreferences/DesktopPreferences.cpp)
target_include_directories(ludash-configuration PUBLIC src)
target_link_libraries(ludash-configuration PUBLIC Qt6::Core)
add_library(ludash-process-runner src/config/CommandRunner/CommandRunner.cpp)
target_include_directories(ludash-process-runner PUBLIC src)
target_link_libraries(ludash-process-runner PUBLIC Qt6::Core)
add_library(ludash-audio-settings src/desktop/AudioSettings/AudioSettings.cpp)
target_include_directories(ludash-audio-settings PUBLIC src)
target_link_libraries(ludash-audio-settings PUBLIC ludash-process-runner)
add_library(ludash-power-settings src/desktop/PowerSettings/PowerSettings.cpp)
target_include_directories(ludash-power-settings PUBLIC src)
target_link_libraries(ludash-power-settings PUBLIC ludash-process-runner)
add_library(ludash-system-tools src/desktop/SystemTools/SystemTools.cpp)
target_include_directories(ludash-system-tools PUBLIC src)
target_link_libraries(ludash-system-tools PUBLIC Qt6::Core)
add_library(ludash-display-settings src/desktop/DisplaySettings/DisplaySettings.cpp)
target_include_directories(ludash-display-settings PUBLIC src)
target_link_libraries(ludash-display-settings PUBLIC Qt6::Gui)
add_library(ludash-input-settings src/desktop/InputSettings/InputSettings.cpp)
target_include_directories(ludash-input-settings PUBLIC src)
target_link_libraries(ludash-input-settings PUBLIC Qt6::WaylandCompositor)
add_library(ludash-shell-modules src/compositor/ShellModules/ShellModules.hpp src/compositor/ShellModuleSchema/ShellModuleSchema.cpp src/compositor/ShellModules/ShellModules.cpp)
target_include_directories(ludash-shell-modules PUBLIC src)
target_link_libraries(ludash-shell-modules PUBLIC Qt6::Core)
qt_add_resources(ludash-shell-modules module_templates PREFIX /LuDash FILES data/modules/templates/panel/Main.qml data/modules/templates/overview/Main.qml)
add_library(ludash-network src/desktop/NetworkStatus/NetworkStatus.cpp)
target_include_directories(ludash-network PUBLIC src)
target_link_libraries(ludash-network PUBLIC Qt6::Network Qt6::DBus)
add_library(ludash-session-environment src/compositor/SessionEnvironment/SessionEnvironment.cpp)
target_include_directories(ludash-session-environment PUBLIC src)
target_link_libraries(ludash-session-environment PUBLIC Qt6::Core Qt6::DBus)
target_compile_definitions(ludash-session-environment PRIVATE LUDASH_ASSET_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}/data/assets")
add_library(ludash-session-actions src/compositor/SessionActions/SessionActions.cpp)
target_include_directories(ludash-session-actions PUBLIC src)
target_link_libraries(ludash-session-actions PUBLIC Qt6::Core Qt6::DBus)
add_library(ludash-shortcut-settings src/desktop/ShortcutSettings/ShortcutSettings.cpp)
target_include_directories(ludash-shortcut-settings PUBLIC src)
target_link_libraries(ludash-shortcut-settings PUBLIC Qt6::Gui)
add_library(ludash-update-check src/compositor/UpdateChecker/UpdateChecker.hpp src/compositor/UpdateChecker/UpdateChecker.cpp)
target_include_directories(ludash-update-check PUBLIC src)
target_link_libraries(ludash-update-check PUBLIC Qt6::Network)
target_compile_definitions(ludash-update-check PRIVATE LUDASH_VERSION="${PROJECT_VERSION}" LUDASH_GIT_COMMIT="${LUNADASH_GIT_COMMIT}")
add_library(ludash-tiling-core src/compositor/tiling/TilingGeometry/TilingGeometry.c)
target_include_directories(ludash-tiling-core PUBLIC src)
add_library(ludash-system-metrics src/compositor/SystemMetrics/SystemMetrics.c)
target_include_directories(ludash-system-metrics PUBLIC src)
add_library(ludash-tiling src/compositor/tiling/TilingLayout/TilingLayout.cpp)
target_include_directories(ludash-tiling PUBLIC src)
target_link_libraries(ludash-tiling PUBLIC ludash-tiling-core Qt6::Core)
add_library(ludash-window-rules src/compositor/WindowRules/WindowRules.cpp)
target_include_directories(ludash-window-rules PUBLIC src)
target_link_libraries(ludash-window-rules PUBLIC Qt6::Core)
add_library(ludash-plugins src/compositor/plugins/PluginManager/PluginManager.cpp)
target_include_directories(ludash-plugins PUBLIC src)
target_link_libraries(ludash-plugins PUBLIC Qt6::Quick)
add_library(ludash-default-applications src/desktop/DefaultApplications/DefaultApplications.cpp)
target_include_directories(ludash-default-applications PUBLIC src)
target_link_libraries(ludash-default-applications PUBLIC ludash-configuration Qt6::Core)
add_library(ludash-file-operations src/desktop/FileOperations/FileOperations.cpp)
target_include_directories(ludash-file-operations PUBLIC src)
target_link_libraries(ludash-file-operations PUBLIC Qt6::Core)
add_library(ludash-apps src/desktop/DesktopTheme/DesktopTheme.cpp src/desktop/ApplicationCatalog/ApplicationCatalog.cpp src/desktop/ApplicationWindow/ApplicationWindow.cpp src/desktop/FileManager/FileManager.cpp src/desktop/FileIcons/FileIcons.cpp src/desktop/FileIconDelegate/FileIconDelegate.cpp src/desktop/Console/Console.cpp src/desktop/SystemMonitor/SystemMonitor.cpp src/desktop/Welcome/Welcome.cpp src/desktop/Launcher/Launcher.cpp src/desktop/PackageManager/PackageManager.cpp src/desktop/PluginSettings/PluginSettings.cpp)
target_include_directories(ludash-apps PUBLIC src)
target_link_libraries(ludash-apps PUBLIC ludash-default-applications ludash-file-operations Qt6::Concurrent ludash-system-metrics ludash-localization ludash-plugins ludash-wallpaper Qt6::Widgets)
target_compile_options(ludash-apps PRIVATE -Wall -Wextra -Wpedantic)
set(LAYER_HEADER ${CMAKE_CURRENT_BINARY_DIR}/wlr-layer-shell-server.h)
set(LAYER_CODE ${CMAKE_CURRENT_BINARY_DIR}/wlr-layer-shell-protocol.c)
add_custom_command(OUTPUT ${LAYER_HEADER} ${LAYER_CODE} COMMAND ${WAYLAND_SCANNER} server-header ${CMAKE_CURRENT_SOURCE_DIR}/protocols/wlr-layer-shell-unstable-v1.xml ${LAYER_HEADER} COMMAND ${WAYLAND_SCANNER} private-code ${CMAKE_CURRENT_SOURCE_DIR}/protocols/wlr-layer-shell-unstable-v1.xml ${LAYER_CODE} DEPENDS protocols/wlr-layer-shell-unstable-v1.xml VERBATIM)
set(SCREENCOPY_HEADER ${CMAKE_CURRENT_BINARY_DIR}/wlr-screencopy-server.h)
set(SCREENCOPY_CODE ${CMAKE_CURRENT_BINARY_DIR}/wlr-screencopy-protocol.c)
add_custom_command(OUTPUT ${SCREENCOPY_HEADER} ${SCREENCOPY_CODE} COMMAND ${WAYLAND_SCANNER} server-header ${CMAKE_CURRENT_SOURCE_DIR}/protocols/wlr-screencopy-unstable-v1.xml ${SCREENCOPY_HEADER} COMMAND ${WAYLAND_SCANNER} private-code ${CMAKE_CURRENT_SOURCE_DIR}/protocols/wlr-screencopy-unstable-v1.xml ${SCREENCOPY_CODE} DEPENDS protocols/wlr-screencopy-unstable-v1.xml VERBATIM)
add_library(ludash-wayland src/compositor/WaylandCompositor/WaylandCompositor.cpp src/compositor/protocols/ProtocolExtensions/ProtocolExtensions.cpp src/compositor/WindowFrame/WindowFrame.cpp src/compositor/input/InputMethodSupport/InputMethodSupport.cpp src/compositor/protocols/LayerShell/LayerShell.cpp src/compositor/protocols/LayerSurface/LayerSurface.cpp src/compositor/protocols/ScreenCapture/ScreenCapture.cpp src/compositor/protocols/ScreenCaptureFrame/ScreenCaptureFrame.cpp src/compositor/ipc/ControlServer/ControlServer.cpp src/compositor/SystemStatus/SystemStatus.cpp src/compositor/ResizeGuideItem/ResizeGuideItem.cpp src/compositor/LuDashUtils/LuDashUtils.cpp ${LAYER_HEADER} ${LAYER_CODE} ${SCREENCOPY_HEADER} ${SCREENCOPY_CODE})
target_include_directories(ludash-wayland PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_compile_definitions(ludash-wayland PRIVATE LUDASH_QML_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}/qml" LUDASH_SCRIPT_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}/scripts")
target_link_libraries(ludash-wayland PUBLIC ludash-session-environment ludash-session-actions ludash-shortcut-settings ludash-update-check ludash-default-applications ludash-shell-modules ludash-display-settings ludash-audio-settings ludash-power-settings ludash-system-tools ludash-input-settings ludash-system-metrics ludash-blur ludash-animation ludash-xwayland ludash-configuration ludash-network ludash-wallpaper ludash-renderer ludash-tiling ludash-window-rules ludash-localization ludash-plugins Qt6::Quick Qt6::Network Qt6::WaylandCompositor PkgConfig::WAYLAND_SERVER)
target_compile_options(ludash-wayland PRIVATE -Wall -Wextra -Wpedantic)
target_link_libraries(ludash-wayland PRIVATE ludash-shell-renderer)
add_library(ludash-client-lifecycle src/compositor/WaylandClientShutdown/WaylandClientShutdown.cpp)
target_include_directories(ludash-client-lifecycle PUBLIC src)
target_link_libraries(ludash-client-lifecycle PUBLIC Qt6::Gui PRIVATE PkgConfig::WAYLAND_CLIENT)
add_executable(ludash-desktop src/desktop/desktop_main.cpp)
target_link_libraries(ludash-desktop PRIVATE ludash-apps ludash-client-lifecycle)
set_target_properties(ludash-desktop PROPERTIES OUTPUT_NAME lunadash-desktop)
add_custom_command(TARGET ludash-desktop POST_BUILD COMMAND ${CMAKE_COMMAND} -E create_symlink $<TARGET_FILE_NAME:ludash-desktop> ${CMAKE_CURRENT_BINARY_DIR}/ludash-desktop)
add_executable(ludash-compositor src/compositor/compositor_main.cpp)
target_link_libraries(ludash-compositor PRIVATE ludash-wayland)
set_target_properties(ludash-compositor PROPERTIES OUTPUT_NAME lunadash-compositor)
add_custom_command(TARGET ludash-compositor POST_BUILD COMMAND ${CMAKE_COMMAND} -E create_symlink $<TARGET_FILE_NAME:ludash-compositor> ${CMAKE_CURRENT_BINARY_DIR}/ludash-compositor)
add_executable(ludashctl src/ctl/control_main.cpp)
target_link_libraries(ludashctl PRIVATE Qt6::Network)
set_target_properties(ludashctl PROPERTIES OUTPUT_NAME lunadashctl)
add_custom_command(TARGET ludashctl POST_BUILD COMMAND ${CMAKE_COMMAND} -E create_symlink $<TARGET_FILE_NAME:ludashctl> ${CMAKE_CURRENT_BINARY_DIR}/ludashctl)
if(LUDASH_BUILD_EXAMPLE_PLUGIN)
    add_library(ludash-fade MODULE src/compositor/plugins/FadePlugin/FadePlugin.hpp src/compositor/plugins/FadePlugin/FadePlugin.cpp)
    target_include_directories(ludash-fade PRIVATE src)
    target_link_libraries(ludash-fade PRIVATE Qt6::Quick)
    set_target_properties(ludash-fade PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/plugins/org.ludash.fade)
    configure_file(data/plugins/fade/metadata.json plugins/org.ludash.fade/metadata.json COPYONLY)
    install(TARGETS ludash-fade LIBRARY DESTINATION ${CMAKE_INSTALL_DATADIR}/ludash/plugins/org.ludash.fade)
    install(FILES data/plugins/fade/metadata.json DESTINATION ${CMAKE_INSTALL_DATADIR}/ludash/plugins/org.ludash.fade)
endif()
configure_file(data/ludash.desktop.in ludash.desktop @ONLY)
configure_file(data/lunadash.desktop.in lunadash.desktop @ONLY)
configure_file(data/lunadash-app.desktop.in lunadash-app.desktop @ONLY)
install(TARGETS ludash-desktop ludash-compositor ludashctl RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/ludash-desktop ${CMAKE_CURRENT_BINARY_DIR}/ludash-compositor ${CMAKE_CURRENT_BINARY_DIR}/ludashctl DESTINATION ${CMAKE_INSTALL_BINDIR})
install(PROGRAMS scripts/lunadash-session scripts/ludash-session scripts/lunadash-clipboard-bridge DESTINATION ${CMAKE_INSTALL_BINDIR})
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/lunadash.desktop ${CMAKE_CURRENT_BINARY_DIR}/ludash.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/wayland-sessions)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/lunadash-app.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
install(DIRECTORY qml/ DESTINATION ${CMAKE_INSTALL_DATADIR}/lunadash/shell)
install(DIRECTORY data/assets/ DESTINATION ${CMAKE_INSTALL_DATADIR}/lunadash/data/assets)
install(FILES data/assets/lunadash.png DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/512x512/apps)
install(DIRECTORY data/wallpapers/ DESTINATION ${CMAKE_INSTALL_DATADIR}/ludash/wallpapers)
install(DIRECTORY data/modules/ DESTINATION ${CMAKE_INSTALL_DATADIR}/ludash/modules)
install(DIRECTORY data/translations/ DESTINATION ${CMAKE_INSTALL_DATADIR}/ludash/translations)
install(FILES src/compositor/plugins/CompositorPlugin/CompositorPlugin.hpp DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/LuDash/plugins)
