add_library(ludash-media src/shell/media/MediaPlayer.cpp)
target_include_directories(ludash-media PUBLIC src)
target_link_libraries(ludash-media PUBLIC Qt6::Core Qt6::DBus)
add_library(ludash-audio-spectrum src/shell/audio/AudioSpectrum.cpp)
target_include_directories(ludash-audio-spectrum PUBLIC src)
target_link_libraries(ludash-audio-spectrum PUBLIC Qt6::Core)
add_executable(ludash-shell-tool src/shell/Main.cpp src/shell/runtime/ShellTool.cpp)
target_include_directories(ludash-shell-tool PRIVATE src)
target_link_libraries(ludash-shell-tool PRIVATE ludash-media ludash-audio-spectrum)
set_target_properties(ludash-shell-tool PROPERTIES OUTPUT_NAME lunadash-shell-tool)
install(TARGETS ludash-shell-tool RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
